FROM stackbrew/busybox:latest
MAINTAINER Isaac Caruso <icaruso21@amherst.edu>

# Create data directory
RUN mkdir /data

# Create /data volume
VOLUME /data

# Pull Git Repos
#RUN git clone https://github.com/trenchproject/Climate-Change-Metabolism.git \
 #   git clone https://github.com/icaruso21/Insect-Phenology-Forecaster.git \
  #  git clone https://github.com/trenchproject/RShiny_robomussels.git \
   # git clone https://github.com/trenchproject/RShiny_Lizards.git \
    #git clone https://github.com/trenchproject/RShiny_BiophysicalModelMap.git \
    #git clone https://github.com/trenchproject/RShiny_PlantPhenology 
